# Generated by Django 3.2.8 on 2021-10-25 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='emai',
            new_name='email',
        ),
    ]
